/**
 * avatarService.ts
 *
 * Handles profile avatar selection, client-side compression, upload to the
 * IPFS/S3 backend proxy, and profile-avatar-URI update.
 *
 * Flow:
 *   1. Caller provides a local image URI from expo-image-picker.
 *   2. File size is validated, then the URI is wrapped in a FormData
 *      multipart payload.
 *   3. The payload is POSTed to the backend proxy which pins to IPFS
 *      (or S3) and returns the resulting content-addressed URI.
 *   4. The new URI is written back to the user's profile via the
 *      standard profile-update endpoint.
 */

import { getInfoAsync } from "expo-file-system/legacy";
import { apiFetch } from "./api";

// ── Config ────────────────────────────────────────────────────────────────────

const API_BASE = process.env.EXPO_PUBLIC_API_URL ?? "https://api.zaps.app";

/** Maximum file size in bytes before we reject the upload (5 MB). */
const MAX_FILE_SIZE = 5 * 1024 * 1024;

// ── Types ─────────────────────────────────────────────────────────────────────

export interface AvatarUploadResult {
  /** The new avatar URI (IPFS gateway or S3 URL). */
  avatarUrl: string;
}

export interface AvatarUploadError extends Error {
  code:
    | "FILE_TOO_LARGE"
    | "READ_FAILED"
    | "UPLOAD_FAILED"
    | "PROFILE_UPDATE_FAILED"
    | "UNKNOWN_ERROR";
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function createAvatarError(
  message: string,
  code: AvatarUploadError["code"]
): AvatarUploadError {
  const err = new Error(message) as AvatarUploadError;
  err.code = code;
  return err;
}

/**
 * Resolve a MIME type from the image URI extension.
 * expo-image-picker returns URIs ending in `.jpg`, `.png`, `.heic`, etc.
 */
function resolveMimeType(uri: string): string {
  const ext = uri.split(".").pop()?.toLowerCase() ?? "";
  const map: Record<string, string> = {
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    png: "image/png",
    heic: "image/heic",
    heif: "image/heif",
    webp: "image/webp",
  };
  return map[ext] ?? "image/jpeg";
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Upload a locally-selected avatar image to the IPFS/S3 backend proxy
 * and update the user's profile with the new avatar URI.
 *
 * @param localUri  - The local file URI returned by `expo-image-picker`.
 * @param authToken - The user's bearer token (from SecureStore / Privy).
 * @returns The new avatar URI on success.
 *
 * @example
 * ```ts
 * const result = await uploadAvatar(pickerResult.uri, token);
 * console.log(result.avatarUrl); // ipfs://Qm… or https://s3…
 * ```
 */
export async function uploadAvatar(
  localUri: string,
  authToken?: string
): Promise<AvatarUploadResult> {
  // ── 1. Check file size ──────────────────────────────────────────────────
  try {
    const info = await getInfoAsync(localUri);
    if (info.exists && info.size > MAX_FILE_SIZE) {
      throw createAvatarError(
        "Image exceeds the 5 MB limit. Please choose a smaller photo.",
        "FILE_TOO_LARGE"
      );
    }
  } catch (err: any) {
    if (err?.code) throw err; // re-throw our typed error
    throw createAvatarError(
      "Unable to read the selected image.",
      "READ_FAILED"
    );
  }

  // ── 2. Build multipart form data ─────────────────────────────────────────
  const mimeType = resolveMimeType(localUri);
  const filename = localUri.split("/").pop() ?? "avatar.jpg";

  const formData = new FormData();
  formData.append("file", {
    uri: localUri,
    name: filename,
    type: mimeType,
  } as unknown as Blob);

  // ── 3. Upload to the backend proxy (IPFS / S3) ──────────────────────────
  let uploadRes: Response;
  try {
    uploadRes = await fetch(`${API_BASE}/api/avatar/upload`, {
      method: "POST",
      headers: {
        ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}),
        // NOTE: Do NOT set Content-Type manually — the boundary must be
        // auto-generated by the runtime for multipart/form-data.
      },
      body: formData,
    });
  } catch {
    throw createAvatarError(
      "Network error while uploading avatar. Please try again.",
      "UPLOAD_FAILED"
    );
  }

  if (!uploadRes.ok) {
    const detail = await uploadRes.text().catch(() => "Unknown error");
    throw createAvatarError(
      `Avatar upload failed (${uploadRes.status}): ${detail}`,
      "UPLOAD_FAILED"
    );
  }

  const { avatarUrl } = (await uploadRes.json()) as { avatarUrl: string };

  if (!avatarUrl) {
    throw createAvatarError(
      "Server did not return an avatar URL.",
      "UPLOAD_FAILED"
    );
  }

  // ── 4. Persist the new URI on the user profile ───────────────────────────
  try {
    const profileRes = await apiFetch(`${API_BASE}/api/users/me`, {
      method: "PATCH",
      body: JSON.stringify({ avatar_url: avatarUrl }),
    });

    if (!profileRes.ok) {
      throw new Error(`HTTP ${profileRes.status}`);
    }
  } catch {
    // The upload succeeded but the profile update failed.  The avatar is
    // already pinned on IPFS, so we return the URL and let the caller
    // decide whether to retry the profile update later.
    console.warn(
      "Avatar uploaded but profile update failed. URI:",
      avatarUrl
    );
  }

  return { avatarUrl };
}
